import type {
  AutomationSummary,
  CodeActivityDay,
  CodeChangeSummaryReport,
} from "@sentry/junior/api/schema";

import type { Conversation } from "../../types";

/*
 * Mock data for the repository page. Records use the real dashboard report
 * types so the page renders through shared components. Change titles are real
 * getsentry/junior PRs. People, numbers, and IDs are made up.
 */

const REPO = "getsentry/junior";
const REPO_URL = `https://github.com/${REPO}`;

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

function mockId(index: number): string {
  return `00000000-0000-4000-8000-${String(index).padStart(12, "0")}`;
}

function activityDays(): CodeActivityDay[] {
  const end = Date.now();
  const created = [
    0, 1, 0, 2, 1, 0, 0, 1, 3, 1, 0, 2, 0, 0, 1, 2, 1, 0, 0, 3, 2, 1, 0, 1, 2,
    4, 1, 0, 3, 2,
  ];
  return created.map((value, index) => {
    const date = new Date(end - (29 - index) * 86_400_000)
      .toISOString()
      .slice(0, 10);
    const merged = Math.max(0, value - (index % 4 === 0 ? 1 : 0));
    return { closed: index % 9 === 4 ? 1 : 0, created: value, date, merged };
  });
}

const people = {
  dc: { email: "david.cramer@example.com", fullName: "David Cramer" },
  ml: { email: "matt.lee@example.com", fullName: "Matt Lee" },
  ac: { email: "alex.chen@example.com", fullName: "Alex Chen" },
  rp: { email: "robin.park@example.com", fullName: "Robin Park" },
  so: { email: "sam.ortiz@example.com", fullName: "Sam Ortiz" },
};

const conversations: Conversation[] = [
  {
    id: "c1",
    displayTitle: "Show Automations as cards",
    activityPreview: {
      createdAt: minutesAgo(25),
      role: "assistant",
      text: "PR #1990 merged after dashboard QA.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.dc, people.ml],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(115),
    lastProgressAt: minutesAgo(25),
    lastSeenAt: minutesAgo(25),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1990`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c2",
    displayTitle: "Opt-in operator SQL tool",
    activityPreview: {
      createdAt: minutesAgo(300),
      role: "assistant",
      text: "Reviewing the read-only guard rails before merge.",
    },
    channel: "C08JRCRAMER",
    channelName: "jr-cramer",
    locationId: "slack:C08JRCRAMER",
    participants: [people.dc],
    status: "active",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(390),
    lastProgressAt: minutesAgo(300),
    lastSeenAt: minutesAgo(300),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1989`,
        label: "junior",
        objectType: "code_change",
        status: "open",
      },
    ],
  },
  {
    id: "c3",
    displayTitle: "Why do router evals flake on CI?",
    activityPreview: {
      createdAt: minutesAgo(540),
      role: "assistant",
      text: "Traced to a shared Redis fixture. Waiting on a repro.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.ac, people.rp, people.ml, people.so],
    status: "failed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(630),
    lastProgressAt: minutesAgo(540),
    lastSeenAt: minutesAgo(540),
    cumulativeDurationMs: 0,
  },
  {
    id: "c4",
    displayTitle: "Segmented pill links for page nav",
    activityPreview: {
      createdAt: minutesAgo(1260),
      role: "assistant",
      text: "Moved sub-navigation to SegmentedNav.",
    },
    channel: "D09MATTLEE",
    participants: [people.ml],
    status: "completed",
    surface: "slack",
    visibility: "private",
    startedAt: minutesAgo(1350),
    lastProgressAt: minutesAgo(1260),
    lastSeenAt: minutesAgo(1260),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1986`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c5",
    displayTitle: "Pause controls for noisy automations",
    activityPreview: {
      createdAt: minutesAgo(2880),
      role: "assistant",
      text: "Added pause and resume with an attention view.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.ac, people.dc],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(2970),
    lastProgressAt: minutesAgo(2880),
    lastSeenAt: minutesAgo(2880),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1982`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c6",
    displayTitle: "Record a demo of the TTS skill",
    activityPreview: {
      createdAt: minutesAgo(1920),
      role: "assistant",
      text: "Closed #1985 in favor of a docs page.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.rp],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(2010),
    lastProgressAt: minutesAgo(1920),
    lastSeenAt: minutesAgo(1920),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1985`,
        label: "junior",
        objectType: "code_change",
        status: "closed",
      },
    ],
  },
  {
    id: "c7",
    displayTitle: "Where does the handoff router pick a profile?",
    activityPreview: {
      createdAt: minutesAgo(2900),
      role: "assistant",
      text: "Explained turn routing in chat/README.",
    },
    channel: "D09MATTLEE",
    participants: [people.so],
    status: "completed",
    surface: "slack",
    visibility: "private",
    startedAt: minutesAgo(2990),
    lastProgressAt: minutesAgo(2900),
    lastSeenAt: minutesAgo(2900),
    cumulativeDurationMs: 0,
  },
  {
    id: "c8",
    displayTitle: "Creator-only edit API for automations",
    activityPreview: {
      createdAt: minutesAgo(4320),
      role: "assistant",
      text: "Added an edit endpoint that checks the creator.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.dc, people.ac],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(4410),
    lastProgressAt: minutesAgo(4320),
    lastSeenAt: minutesAgo(4320),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1980`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c9",
    displayTitle: "Gemini narration through AI Gateway",
    activityPreview: {
      createdAt: minutesAgo(5760),
      role: "assistant",
      text: "Wired TTS through Vercel AI Gateway.",
    },
    channel: "C08JRCRAMER",
    channelName: "jr-cramer",
    locationId: "slack:C08JRCRAMER",
    participants: [people.dc],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(5850),
    lastProgressAt: minutesAgo(5760),
    lastSeenAt: minutesAgo(5760),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1969`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c10",
    displayTitle: "Linear cards lost their descriptions",
    activityPreview: {
      createdAt: minutesAgo(7200),
      role: "assistant",
      text: "Restored ticket descriptions on annotation cards.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.ml, people.rp],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(7290),
    lastProgressAt: minutesAgo(7200),
    lastSeenAt: minutesAgo(7200),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1968`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c11",
    displayTitle: "Check prompt cache write volume",
    activityPreview: {
      createdAt: minutesAgo(8640),
      role: "assistant",
      text: "Found the cache write spike. Fixed in #1956.",
    },
    channel: "C08JRCRAMER",
    channelName: "jr-cramer",
    locationId: "slack:C08JRCRAMER",
    participants: [people.dc],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(8730),
    lastProgressAt: minutesAgo(8640),
    lastSeenAt: minutesAgo(8640),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1956`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
  {
    id: "c12",
    displayTitle: "Share a conversation from the dashboard",
    activityPreview: {
      createdAt: minutesAgo(8700),
      role: "assistant",
      text: "Added share actions to the conversation header.",
    },
    channel: "C07PROJJUNIOR",
    channelName: "proj-junior",
    locationId: "slack:C07PROJJUNIOR",
    participants: [people.ml],
    status: "completed",
    surface: "slack",
    visibility: "public",
    startedAt: minutesAgo(8790),
    lastProgressAt: minutesAgo(8700),
    lastSeenAt: minutesAgo(8700),
    cumulativeDurationMs: 0,
    sidebarAnnotations: [
      {
        key: `${REPO}#1962`,
        label: "junior",
        objectType: "code_change",
        status: "merged",
      },
    ],
  },
];

const changes: CodeChangeSummaryReport[] = [
  {
    id: mockId(1),
    number: 1991,
    title: "Link repository rows to a detail page",
    state: "open",
    openedAt: minutesAgo(12),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1991`,
  },
  {
    id: mockId(2),
    number: 1990,
    title: "Show Automations as cards instead of table rows",
    state: "merged",
    openedAt: minutesAgo(25),
    mergedAt: minutesAgo(20),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1990`,
  },
  {
    id: mockId(3),
    number: 1989,
    title: "Add opt-in runOperatorSql tool",
    state: "open",
    openedAt: minutesAgo(300),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1989`,
  },
  {
    id: mockId(4),
    number: 1986,
    title: "Use segmented pill links for page navigation",
    state: "merged",
    openedAt: minutesAgo(1260),
    mergedAt: minutesAgo(1255),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1986`,
  },
  {
    id: mockId(5),
    number: 1985,
    title: "Add reusable demo video workflow",
    state: "closed",
    openedAt: minutesAgo(1920),
    closedAt: minutesAgo(1915),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1985`,
  },
  {
    id: mockId(6),
    number: 1982,
    title: "Add pause controls and attention view",
    state: "merged",
    openedAt: minutesAgo(2880),
    mergedAt: minutesAgo(2875),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1982`,
  },
  {
    id: mockId(7),
    number: 1980,
    title: "Add safe creator-only edit API",
    state: "merged",
    openedAt: minutesAgo(4320),
    mergedAt: minutesAgo(4315),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1980`,
  },
  {
    id: mockId(8),
    number: 1978,
    title: "Search and page the full accessible collection",
    state: "merged",
    openedAt: minutesAgo(4400),
    mergedAt: minutesAgo(4395),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1978`,
  },
  {
    id: mockId(9),
    number: 1976,
    title: "Make automation rows easy to scan",
    state: "merged",
    openedAt: minutesAgo(5700),
    mergedAt: minutesAgo(5695),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1976`,
  },
  {
    id: mockId(10),
    number: 1969,
    title: "Add Gemini narration through Vercel AI Gateway",
    state: "merged",
    openedAt: minutesAgo(5760),
    mergedAt: minutesAgo(5755),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1969`,
  },
  {
    id: mockId(11),
    number: 1968,
    title: "Restore Linear cards and ticket descriptions",
    state: "merged",
    openedAt: minutesAgo(7200),
    mergedAt: minutesAgo(7195),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1968`,
  },
  {
    id: mockId(12),
    number: 1962,
    title: "Add conversation share actions",
    state: "merged",
    openedAt: minutesAgo(8700),
    mergedAt: minutesAgo(8695),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1962`,
  },
  {
    id: mockId(13),
    number: 1956,
    title: "Reduce prompt cache writes",
    state: "merged",
    openedAt: minutesAgo(8640),
    mergedAt: minutesAgo(8635),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1956`,
  },
  {
    id: mockId(14),
    number: 1958,
    title: "Retry flaky router eval fixture",
    state: "closed",
    openedAt: minutesAgo(10080),
    closedAt: minutesAgo(10075),
    provider: "github",
    repository: REPO,
    url: `${REPO_URL}/pull/1958`,
  },
];
const projJunior = {
  channelId: "C07PROJJUNIOR",
  label: "#proj-junior",
  teamId: "T01SENTRY",
  visibility: "public",
} as const;

const automations: AutomationSummary[] = [
  {
    kind: "event",
    id: "a1",
    title: "Fix failing checks on Junior PRs",
    instruction:
      "When checks fail on a Junior PR, find the cause and push a fix.",
    source: "github",
    resource: REPO,
    events: ["pull_request.checks.failed"],
    triggerAvailable: true,
    status: "active",
    createdAt: minutesAgo(40_000),
    createdBy: people.dc.fullName,
    createdByEmail: people.dc.email,
    credentialMode: "creator",
    destination: projJunior,
    lastRunAt: minutesAgo(180),
    lastRunStatus: "completed",
    outcomes: [],
    ownedByViewer: false,
    runs: { 1: 2, 7: 6, 30: 14, 90: 31 },
    totalRuns: 31,
  },
  {
    kind: "event",
    id: "a2",
    title: "Address review comments",
    instruction:
      "When a reviewer requests changes on a Junior PR, address them.",
    source: "github",
    resource: REPO,
    events: ["pull_request.review.changes_requested"],
    triggerAvailable: true,
    status: "active",
    createdAt: minutesAgo(30_000),
    createdBy: people.ml.fullName,
    createdByEmail: people.ml.email,
    credentialMode: "creator",
    destination: projJunior,
    lastRunAt: minutesAgo(300),
    lastRunStatus: "failed",
    outcomes: [],
    ownedByViewer: false,
    runs: { 1: 1, 7: 3, 30: 9, 90: 12 },
    totalRuns: 12,
  },
  {
    kind: "event",
    id: "a3",
    title: "Self-update to latest release",
    instruction:
      "When a Junior release is published, open a PR that updates to it.",
    source: "github",
    resource: REPO,
    events: ["release.published"],
    triggerAvailable: true,
    status: "active",
    createdAt: minutesAgo(60_000),
    createdBy: people.dc.fullName,
    createdByEmail: people.dc.email,
    credentialMode: "creator",
    destination: projJunior,
    lastRunAt: minutesAgo(2_880),
    lastRunStatus: "completed",
    outcomes: [],
    ownedByViewer: false,
    runs: { 1: 0, 7: 1, 30: 4, 90: 11 },
    totalRuns: 11,
  },
  {
    kind: "event",
    id: "a4",
    title: "Triage new bug issues",
    instruction: "Label new bug issues and ask for missing reproduction steps.",
    source: "github",
    resource: REPO,
    events: ["issue.opened"],
    triggerAvailable: true,
    status: "paused",
    createdAt: minutesAgo(20_000),
    createdBy: people.ac.fullName,
    createdByEmail: people.ac.email,
    credentialMode: "creator",
    destination: projJunior,
    lastRunAt: minutesAgo(9_000),
    lastRunStatus: "completed",
    outcomes: [],
    ownedByViewer: false,
    runs: { 1: 0, 7: 0, 30: 3, 90: 8 },
    totalRuns: 8,
  },
];

/** Mock repository detail report. */
export const repositoryMock = {
  owner: "getsentry",
  name: "junior",
  url: REPO_URL,
  defaultBranch: "main",
  lastActivityAt: minutesAgo(25),
  workspaces: [
    { id: "4f7c2a9e-1b3d-4c6e-8a1f-2d9b7e5c3a10", name: "junior" },
    { id: "9a1e6d4b-7c2f-4e8a-b3d5-6f0c8e2a4b71", name: "dashboard-qa" },
  ],
  stats: {
    conversations: 64,
    people: 11,
    created: 31,
    merged: 24,
    open: 4,
    closed: 3,
    automations: automations.length,
    costUsd: 212.4,
    tokens: 48_200_000,
    durationMs: 112_320_000,
    perMergedChangeUsd: 6.1,
  },
  activityDays: activityDays(),
  conversations: [...conversations].sort((a, b) =>
    b.lastSeenAt.localeCompare(a.lastSeenAt),
  ),
  changes,
  automations,
  usage: {
    people: [
      { actor: people.dc, conversations: 22, costUsd: 84.2 },
      { actor: people.ml, conversations: 13, costUsd: 41.6 },
      { actor: people.ac, conversations: 9, costUsd: 22.9 },
      { actor: people.rp, conversations: 6, costUsd: 12.1 },
    ],
    conversations: [
      { id: "c5", title: "Pause controls for noisy automations", costUsd: 7.9 },
      {
        id: "c8",
        title: "Creator-only edit API for automations",
        costUsd: 6.12,
      },
      { id: "c9", title: "Gemini narration through AI Gateway", costUsd: 5.47 },
      { id: "c2", title: "Opt-in operator SQL tool", costUsd: 5.08 },
      { id: "c6", title: "Record a demo of the TTS skill", costUsd: 4.35 },
    ],
    automations: [
      { id: "a1", title: "Fix failing checks on Junior PRs", costUsd: 21.3 },
      { id: "a2", title: "Address review comments", costUsd: 12.4 },
      { id: "a3", title: "Self-update to latest release", costUsd: 9.8 },
      { id: "a4", title: "Triage new bug issues", costUsd: 4.2 },
    ],
  },
};
