export const COMMAND_PROXY_ACTIVE_PROVIDERS_ENV =
  "JUNIOR_COMMAND_PROXY_ACTIVE_PROVIDERS";
export const COMMAND_PROXY_AUTH_REQUIRED_PROVIDERS_ENV =
  "JUNIOR_COMMAND_PROXY_AUTH_REQUIRED_PROVIDERS";
