import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    app: "src/app.ts",
    "cli/env": "src/cli/env.ts",
    "cli/main": "src/cli/main.ts",
    "cli/plugins": "src/cli/plugins.ts",
    "cli/init": "src/cli/init.ts",
    "cli/run": "src/cli/run.ts",
    "cli/chat": "src/cli/chat.ts",
    "cli/check": "src/cli/check.ts",
    "cli/upgrade": "src/cli/upgrade.ts",
    "cli/snapshot-create": "src/cli/snapshot-create.ts",
    api: "src/api.ts",
    "api/schema": "src/api/schema.ts",
    instrumentation: "src/instrumentation.ts",
    nitro: "src/nitro.ts",
    vercel: "src/vercel.ts",
    version: "src/version.ts",
  },
  format: "esm",
  tsconfig: "tsconfig.build.json",
  dts: {
    entry: {
      app: "src/app.ts",
      api: "src/api.ts",
      "api/schema": "src/api/schema.ts",
      instrumentation: "src/instrumentation.ts",
      nitro: "src/nitro.ts",
      vercel: "src/vercel.ts",
      version: "src/version.ts",
    },
    compilerOptions: {
      // TODO(upstream): Remove after tsup stops adding deprecated baseUrl.
      ignoreDeprecations: "6.0",
    },
  },
  outDir: "dist",
  clean: true,
  splitting: true,
  external: [
    "#junior/config",
    "hono",
    "@sentry/node",
    // All runtime npm dependencies stay external
    "@agentclientprotocol/sdk",
    "@ai-sdk/gateway",
    "@chat-adapter/slack",
    "@chat-adapter/state-memory",
    "@chat-adapter/state-redis",
    "@earendil-works/pi-agent-core",
    "@earendil-works/pi-ai",
    "@sinclair/typebox",
    "@slack/web-api",
    "@vercel/functions",
    "@vercel/oidc",
    "@vercel/queue",
    "@vercel/sandbox",
    "ai",
    "chat",
    "commander",
    "just-bash",
    "node-html-markdown",
    "yaml",
    "zod",
  ],
});
