import type { ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { codeToHtml, type BundledLanguage } from "shiki/bundle/web";

import { cn } from "./styles";
import {
  buildSearchDecorations,
  useTranscriptSearch,
} from "./conversations/transcriptSearch";

declare const shikiHtmlBrand: unique symbol;

/** HTML generated by Shiki and safe to pass to the highlighted code shell. */
export type ShikiHtml = string & { readonly [shikiHtmlBrand]: true };

/**
 * Render highlighted code while keeping Shiki output responsive in transcripts.
 * Automatically applies active transcript search highlights from context.
 */
export function HighlightedCode(props: {
  code: string;
  language: BundledLanguage;
}) {
  const search = useTranscriptSearch();
  const normalizedQuery = search.active ? search.normalizedQuery : undefined;
  const highlighted = useQuery({
    queryKey: ["highlight", props.language, props.code, normalizedQuery],
    queryFn: async (): Promise<ShikiHtml> => {
      const decorations = normalizedQuery
        ? buildSearchDecorations(props.code, normalizedQuery)
        : [];
      return (await codeToHtml(props.code, {
        decorations: decorations.length ? decorations : undefined,
        lang: props.language,
        theme: "github-dark",
      })) as ShikiHtml;
    },
    staleTime: Infinity,
  });

  if (!highlighted.data) {
    return <HighlightedCodeFallback>{props.code}</HighlightedCodeFallback>;
  }

  return <HighlightedCodeHtml html={highlighted.data} />;
}

/** Render unhighlighted code in the same responsive frame as Shiki output. */
export function HighlightedCodeFallback(props: {
  children: ReactNode;
  variant?: "code" | "prose";
}) {
  return (
    <pre
      className={cn(
        "m-0 min-w-0 whitespace-pre-wrap break-words bg-transparent p-0 text-dashboard-text",
        props.variant === "prose"
          ? "font-display text-base leading-7"
          : "font-mono text-sm leading-relaxed",
      )}
    >
      <code>{props.children}</code>
    </pre>
  );
}

/** Render trusted Shiki HTML with transcript-safe responsive wrapping. */
export function HighlightedCodeHtml(props: {
  html: ShikiHtml;
  variant?: "code" | "prose";
}) {
  return (
    <div
      className={cn(
        "min-w-0 overflow-hidden [&_.line]:block [&_.line]:max-w-full [&_.line]:whitespace-pre-wrap [&_.line]:break-words [&_.line]:[overflow-wrap:anywhere] [&_code]:block [&_code]:max-w-full [&_code]:whitespace-normal [&_code]:break-words [&_code]:[overflow-wrap:anywhere] [&_pre]:!m-0 [&_pre]:!max-w-full [&_pre]:!overflow-hidden [&_pre]:!bg-transparent [&_pre]:!p-0 [&_pre]:whitespace-normal [&_pre]:break-words [&_pre]:[overflow-wrap:anywhere] [&_span]:whitespace-pre-wrap [&_span]:break-words [&_span]:[overflow-wrap:anywhere] [&_mark.search-match]:bg-amber-400/20 [&_mark.search-match]:rounded-[2px] [&_mark.search-match]:text-inherit [&_mark.search-match]:not-italic",
        props.variant === "prose"
          ? "[&_pre]:font-display [&_pre]:text-base [&_pre]:leading-7"
          : "[&_pre]:font-mono [&_pre]:text-sm [&_pre]:leading-relaxed",
      )}
      dangerouslySetInnerHTML={{ __html: props.html }}
    />
  );
}
