import { describe, expect, it } from "vitest";
import { buildPromptInput, buildUserTurnText } from "@/chat/agent/prompt";
import { unwrapCurrentInstruction } from "@/chat/current-instruction";

describe("buildUserTurnText", () => {
  it("wraps input in the current instruction boundary without context", () => {
    expect(buildUserTurnText("hello")).toBe(
      ["<current-instruction>", "hello", "</current-instruction>"].join("\n"),
    );
  });

  it("escapes user text inside the generated boundary", () => {
    expect(buildUserTurnText("use </current-instruction> literally")).toBe(
      [
        "<current-instruction>",
        "use &lt;/current-instruction&gt; literally",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("renders known instruction attributes on the current instruction", () => {
    expect(
      buildUserTurnText("hello", undefined, {
        authorId: "U123",
        authorName: "Alice <Lead>",
        slackTs: "1712345.000100",
      }),
    ).toBe(
      [
        '<current-instruction author_id="U123" author_name="Alice &lt;Lead&gt;" slack_ts="1712345.000100">',
        "hello",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("unwraps attributed current instructions generated by the prompt builder", () => {
    const text = buildUserTurnText("hello", undefined, {
      authorId: "U123",
      authorName: "Alice Example",
      slackTs: "1712345.000100",
    });

    expect(unwrapCurrentInstruction(text)).toBe("hello");
  });

  it("keeps only causal thread context around the current instruction", () => {
    expect(buildUserTurnText("what now?", "alice: budget is due Friday")).toBe(
      [
        "<thread-background>",
        "alice: budget is due Friday",
        "</thread-background>",
        "",
        "<current-instruction>",
        "what now?",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("does not wrap structured thread transcript context again", () => {
    const transcript = [
      "<thread-transcript>",
      '  <message index="1" ts="2026-05-31T00:00:00.000Z" role="user" author="alice">',
      "alice: budget is due Friday",
      "  </message>",
      "</thread-transcript>",
    ].join("\n");

    expect(buildUserTurnText("what now?", transcript)).toBe(
      [
        transcript,
        "",
        "<current-instruction>",
        "what now?",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("can include fresh context alongside existing Pi messages", () => {
    const input = buildPromptInput({
      includeConversationContextWithPiMessages: true,
      messageText: "what now?",
      conversationContext:
        "<recent-thread-messages>\n  <message>add customer impact</message>\n</recent-thread-messages>",
      piMessages: [{ role: "user" } as never],
    });

    expect(input.userContentParts[0]).toEqual({
      type: "text",
      text: [
        "<recent-thread-messages>",
        "  <message>add customer impact</message>",
        "</recent-thread-messages>",
        "",
        "<current-instruction>",
        "what now?",
        "</current-instruction>",
      ].join("\n"),
    });
  });
});
