import { describe, expect, it } from "vitest";
import {
  buildPromptInput,
  buildUserTurnText,
  renderExplicitSkillInstructions,
} from "@/chat/agent/prompt";
import { unwrapCurrentInstruction } from "@/chat/current-instruction";

describe("buildUserTurnText", () => {
  it("renders an explicitly selected skill as loaded instructions", () => {
    expect(
      renderExplicitSkillInstructions({
        name: "weather-lookup",
        description: "Weather lookup",
        skillPath: "/host/skills/weather-lookup/SKILL.md",
        body: "Use the weather source.",
      }),
    ).toBe(
      [
        "<skill>",
        "<name>weather-lookup</name>",
        "<path>/vercel/sandbox/skills/weather-lookup/SKILL.md</path>",
        "<working_directory>/vercel/sandbox/skills/weather-lookup</working_directory>",
        "<path_resolution>Resolve relative paths in this skill against /vercel/sandbox/skills/weather-lookup. For bash commands from this skill, cd to /vercel/sandbox/skills/weather-lookup first or use absolute paths.</path_resolution>",
        "Use the weather source.",
        "</skill>",
      ].join("\n"),
    );
  });

  it("wraps input in the current instruction boundary without context", () => {
    expect(buildUserTurnText("hello")).toBe(
      ["<current-instruction>", "hello", "</current-instruction>"].join("\n"),
    );
  });

  it("escapes user text inside the generated boundary", () => {
    expect(buildUserTurnText("use </current-instruction> literally")).toBe(
      [
        "<current-instruction>",
        "use &lt;/current-instruction&gt; literally",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("renders known instruction attributes on the current instruction", () => {
    expect(
      buildUserTurnText("hello", {
        authorId: "U123",
        authorName: "Alice <Lead>",
        slackTs: "1712345.000100",
      }),
    ).toBe(
      [
        '<current-instruction author_id="U123" author_name="Alice &lt;Lead&gt;" slack_ts="1712345.000100">',
        "hello",
        "</current-instruction>",
      ].join("\n"),
    );
  });

  it("unwraps attributed current instructions generated by the prompt builder", () => {
    const text = buildUserTurnText("hello", {
      authorId: "U123",
      authorName: "Alice Example",
      slackTs: "1712345.000100",
    });

    expect(unwrapCurrentInstruction(text)).toBe("hello");
  });

  it("keeps thread context separate from the current instruction", () => {
    const input = buildPromptInput({
      instruction: {
        text: "what now?",
        context:
          "<recent-thread-messages>\n  <message>add customer impact</message>\n</recent-thread-messages>",
        includeConversationContextWithHistory: true,
      },
      history: [{ role: "user" } as never],
    });

    expect(input.contextContentParts).toEqual([
      {
        type: "text",
        text: [
          '<thread-context authority="evidence-only">',
          "<recent-thread-messages>",
          "  <message>add customer impact</message>",
          "</recent-thread-messages>",
          "</thread-context>",
        ].join("\n"),
      },
    ]);
    expect(input.userContentParts[0]).toEqual({
      type: "text",
      text: [
        "<current-instruction>",
        "what now?",
        "</current-instruction>",
      ].join("\n"),
    });
  });

  it("marks unstructured thread background as evidence only", () => {
    const input = buildPromptInput({
      instruction: {
        text: "summarize",
        context: "earlier humans discussed filing a ticket",
        includeConversationContextWithHistory: true,
      },
      history: [{ role: "user" } as never],
    });

    expect(input.contextContentParts).toEqual([
      {
        type: "text",
        text: [
          '<thread-context authority="evidence-only">',
          "earlier humans discussed filing a ticket",
          "</thread-context>",
        ].join("\n"),
      },
    ]);
  });
});
